### ISSUE TITLE
Test multidenom SFS staking on testnet (having multiple pools, that rewards work as expected, TWAP updates don't conflict, etc.)

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/osmosis#1032]

**Comment by daniel-farina** [comment]
@czarcas7ic  could you please add the results from your local test and any additional follow ups.

**Comment by czarcas7ic** [comment]
@daniel-farina @ValarDragon Just did the tests we discussed and it appears all is working as it should be. I showed my work below, please let me know if there is any further questions or if I should test anything else!

# Testing Multidenom SFS on Testnet

Three validators with three seperate wallets
```
validator1 = osmo1e9udphr2xjpf2lufxah2fek6nnqf6g8396syt6
validator2 = osmo18z7mka8njlwxmv36cylxa3wthz00djandxm4ac
validator3 = osmo183jwpmnflq0m8k6mvknegnxsryqsut3w33ngcz
```


Created two pools, both with the same specs
```
{
	"weights": "5stake,5uosmo",
	"initial-deposit": "1000000stake,1000000uosmo",
	"swap-fee": "0.01",
	"exit-fee": "0.01",
	"future-governor": "168h"
}
```

Passed gov prop to add gamm/pool/1 and gamm/pool/2

Checked operator addresses of all three validators
```
validator1 = osmovaloper1e9udphr2xjpf2lufxah2fek6nnqf6g83ldc8ua
validator2 = osmovaloper18z7mka8njlwxmv36cylxa3wthz00djanh3nk2l
validator3 = osmovaloper183jwpmnflq0m8k6mvknegnxsryqsut3wtxmt09
```

****


User 1 - Locks just in gamm/pool/1

User 2 - Locks just in gamm/pool/2

User 3 - Locks in both gamm/pool/1 and gamm/pool/2
```
osmosisd tx lockup lock-tokens 5000000000000000000gamm/pool/1 --duration=360h --from=validator1 --keyring-backend=test --chain-id=testing --broadcast-mode=block --yes --home=$HOME/.osmosisd/validator1

osmosisd tx lockup lock-tokens 5000000000000000000gamm/pool/2 --duration=360h --from=validator2 --keyring-backend=test --chain-id=testing --broadcast-mode=block --yes --home=$HOME/.osmosisd/validator2

osmosisd tx lockup lock-tokens 5000000000000000000gamm/pool/1 --duration=360h --from=validator3 --keyring-backend=test --chain-id=testing --broadcast-mode=block --yes --home=$HOME/.osmosisd/validator3

osmosisd tx lockup lock-tokens 5000000000000000000gamm/pool/2 --duration=360h --from=validator3 --keyring-backend=test --chain-id=testing --broadcast-mode=block --yes --home=$HOME/.osmosisd/validator3
```


****
Superfluid stake all four locks in same epoch

Ensure epoch just started
```
osmosisd q epochs epoch-infos
```

SFS all four locks
```
osmosisd tx superfluid delegate 1 osmovaloper183jwpmnflq0m8k6mvknegnxsryqsut3wtxmt09 --from=validator1 --keyring-backend=test --chain-id=testing --broadcast-mode=block --yes --home=$HOME/.osmosisd/validator1

osmosisd tx superfluid delegate 2 osmovaloper183jwpmnflq0m8k6mvknegnxsryqsut3wtxmt09 --from=validator2 --keyring-backend=test --chain-id=testing --broadcast-mode=block --yes --home=$HOME/.osmosisd/validator2

osmosisd tx superfluid delegate 3 osmovaloper1e9udphr2xjpf2lufxah2fek6nnqf6g83ldc8ua --from=validator1 --keyring-backend=test --chain-id=testing --broadcast-mode=block --yes --home=$HOME/.osmosisd/validator1

osmosisd tx superfluid delegate 4 osmovaloper18z7mka8njlwxmv36cylxa3wthz00djanh3nk2l --from=validator1 --keyring-backend=test --chain-id=testing --broadcast-mode=block --yes --home=$HOME/.osmosisd/validator1
```

Epoch 129 (Height 1432)
User 1 - 227 uosmo
User 2 - 227 uosmo
User 3 - 416 uosmo

Epoch 130 (Height 1434)
User 1 - 262 uosmo (inc of 35)
User 2 - 262 uosmo (inc of 35)
User 3 - 474 uosmo (inc of 58)


Update pool 1 spot price by doing a swap into the pool
Starts with 1000000uosmo and 1000000stake
Will swap 100000uosmo into pool 1. This ended up changing ratio to 909919stake and 1100000uosmo

```
osmosisd tx gamm swap-exact-amount-in 100000uosmo 50000 --swap-route-pool-ids=1 --swap-route-denoms=stake --from=validator1 --keyring-backend=test --chain-id=testing --yes --home=$HOME/.osmosisd/validator1
```

Epoch 161
User 1 - 1130
User 2 - 1128
User 3 - 2130

Epoch 162
User 1 - 1162 (inc 32)
User 2 - 1156 (inc 28)
User 3 - 2194 (inc 64)

Spot price increase for pool 1 is reflected in User 1's increased payout

Did much larger swap into pool 1, resulting in ratio to become 478905stake and 2100000usmo.

Epoch 167
User 1 - 1238
User 2 - 1224
User 3 - 2314

Epoch 168
User 1 - 1285 (inc 47)
User 2 - 1252 (inc 28)
User 3 - 2395 (inc 81)

**Comment by ValarDragon** [comment]
Oh sweet! I have a suspition for what these increases are for! It could be the proposer bonus inside of x/distribution. By default the max proposer bonus is `5%`. (See here: https://github.com/osmosis-labs/cosmos-sdk/blob/v0.45.0x-osmo-v7/x/distribution/types/params.go)

Since there are three validators, this means that a non-proposer gets an amount on the order of `95% / 3 = 31.66%`. A proposer gets `5% + 31.66% = 36.66%`. We can test if our numbers confirm this suspicion, by checking if `low_amount / 31.66 ~= high_amount / 36.66%` for user 1 or user 2 (as they're to the same validator). Spot checking this with 227, 262 we get:

```
227 / 31.66% = 716.8
262 / 36.66% = 714.5
```

The difference seems like its just rounding error. (as distribution would truncate the 227 and 262.

**Comment by ValarDragon** [comment]
Sweet thanks for testing this! 

I'm having a bit of trouble understanding why in the small swap to pool 1, user 1's reward that epoch went down, and user 2's went down. (But user 3 went up) It could be the proposer bonus inside of x/distribution. By default the max proposer bonus is `5%`. (See here: https://github.com/osmosis-labs/cosmos-sdk/blob/v0.45.0x-osmo-v7/x/distribution/types/params.go)

Since user 3 delegates to a diff validator, the validator proposer bonus could explain this?

In the third case, we see a relation that I think makes sense! (user 1 goes up, 2 goes down, 3 goes up. Confusingly 3 != user 1 + user 2, maybe rounding error or proposer bonus)

**Comment by czarcas7ic** [comment]
Hm okay, let me do another test where instead I make all the delegations from non validators to a single validator so any proposal bonuses will be constant

**Comment by ValarDragon** [comment]
or we can set the proposer bonus param to 0

**Comment by czarcas7ic** [comment]
@ValarDragon I was already halfway though doing this with a single validator when you made this comment, so I finished it up and it makes more sense than the last test.

# Results

Epoch 93 (Height 1101)
User 1 - 88 uosmo
User 2 - 88 uosmo
User 3 - 176 uosmo

Epoch 94 (Height 1113)
User 1 - 176 uosmo (inc of 88)
User 2 - 176 uosmo (inc of 88)
User 3 - 352 uosmo (inc of 176)


Update pool 1 spot price by doing a large swap into the pool
Starts with 1000000uosmo and 1000000stake
Swaped 900000uosmo into pool 1. This ended up changing ratio to 528821stake and 1900000uosmo

```
osmosisd tx gamm swap-exact-amount-in 900000uosmo 100000 --swap-route-pool-ids=1 --swap-route-denoms=stake --from=validator1 --keyring-backend=test --chain-id=testing --yes --home=$HOME/.osmosisd/validator1
```

Did the swap at height 1166 (Epoch 98)


Epoch 98 (Height 1161)
User 1 - 528
User 2 - 528
User 3 - 1056


Next Epoch showed no change


Epoch 99 (Height 1173)
User 1 - 616 (inc 88)
User 2 - 616 (inc 88)
User 3 - 1232 (inc 176)


Epoch after this, spot price increase for pool 1 is reflected in User 1's increased payout

Epoch 100 (Height 1185)
User 1 - 783 (inc 167)
User 2 - 704 (inc 88)
User 3 - 1487 (inc 255)

**Comment by ValarDragon** [comment]
Amazing! Thanks so much for testing this rigorously! I think we're set then

**Comment by ValarDragon** [comment]
So user 2 didn't go down in the final epoch, this makes sense if the overall amount of superfluid staking increase was a bit negligible as compared to the total amount staked. (e.g. due to validator self bonds)

Just to sanity check what were the validator self bonds in stake amounts? Was it on the order of like `1_000_000_000` (or more) stake? If so, I think we're good.

**Comment by czarcas7ic** [comment]
If you are asking about the first test, validator 1 and 2 has a self bond amount of 500000000uosmo while validator 3 has a self bond of 400000000uosmo. On the last test, the single validator had a self bond of 500000000uosmo.

**Comment by ValarDragon** [comment]
perfect! Then I think the numbers make sense. (We'd have expected user 2 staker rewards to go down by approximately `1_000_000 / 500_000_000 = 1/500 = .2%`, but `.2%.* 88 = 0` hence we see no change!

I think this is working then, and were set

**Comment by czarcas7ic** [comment]
Awesome! Thanks again for stepping me through the process the other day! Will now close 😄
