### ISSUE TITLE
Make test scaffolding for superfluid

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/osmosis#1033]
@ValarDragon  to add more details

@mattverse  already doing some work on this.

**Comment by ValarDragon** [comment]
I think as a general guide, we want to have re-usable helper methods, where a module like superfluid doesn't have to reason about the deep internals of other modules. Furthermore, we want to use logic as close to the state machines as possible, for instance when we lock tokens, use MsgLockTokens, unless we're trying to deliberately setup ourselves in a weird state. (Similar for CreateValidator w/ staking, or for running an epoch we should use BeginBlock). We already have helper methods for CreateValidator & BeginBlock in the `apptesting` module.

Concretely, superfluid shouldn't really be directly constructing PoolParams or PoolAssets, or doing swaps to alter spot price. These should be callouts to testing helper methods in the gamm module.

Right now the superfluid tests are complex because they:
* Don't re-use common helper methods
* Use methods that should be relatively internal to the module in the re-used setup code. (E.g. Setting the spot price of a pool by overriding the superfluid state entry for it, rather than updating the gamm pool to emit a different spot price)
* Use a different flow than messages would be using (This could moreso be the lockup modules fault, with the message server not just being a wrapper around the keeper function)

So I think the next steps are:
- [ ] Create a way for being able to define re-usable test helper methods across the codebase
  - #1008 was a first solution for this. I think we should try changing that interface to a struct that we embed in each module's test_suite struct, and see how the API / usability compares. A decision regarding struct vs interface suffices imo for considering this done.
- [ ] Make test helper methods in Gamm that allow setting the spot price of a pool, via minting to a dummy address and doing a swap. Similarly, make it easy to make pool with default fees, 0 fees.
- [ ] Doing similar for lock tokens helper methods going to a `lockuptesting` rather than being in superfluid 
- [ ] Adding RefreshIntermediaryDelegation tests to Superfluid
- [ ] Adding distribution rewards tests with parameterized multi-epoch 'scenarios'. (Bondings to various pool, asset pairs)

**Comment by mattverse** [comment]
> Make an example balancertesting module that has publicly exposed methods for the suite

Do we have to make a separate package for balancer testing instead of using apptetsing?
Since apptesting package would be at top hierarchy, would we not  be having circular reference?

**Comment by ValarDragon** [comment]
Per discussion on thursday call, last component was RefresHIntermediaryDelegations
