### ISSUE TITLE
[E2E - Upgrade Testing] Add CI pipelines to test upgrades and chain integrity post-upgrade

### ISSUE THREAD

**Issue by nikever** [osmosis-labs/osmosis#1235]
**Background**

Now that we have a e2e testing process in place to the test basic functionality of the chain, we can expand our test suite to test chain upgrades and make sure that basic properties are being preserved after the update

**Tasks**

- #1293 
- #1330
- #1332 
- #1338
- #1333 
- #1414 
- #1415

**Acceptance Criteria**

- Have an automated flow to test an upgrade and perform basic tests after the upgrade to ensure chain integrity.

**Comment by faddat** [comment]
@nikever do you have a way around the github self-hosted runners lack of concurrency / extreme expense of the permium runners they sell?

basically, since their runners really do not match up to the performance of what most node operators use, I am not sure that this path can work, unless we are restricting the state that is used somehow (genesis export maybe?)

**Comment by ValarDragon** [comment]
Can we close this issue? cc @p0mvn
