### ISSUE TITLE
account sequence mismatch, expected 396794, got 396795: incorrect account sequence

### ISSUE THREAD

**Issue by cocoyes** [osmosis-labs/osmosis#1271]
please??? my money is dimiss

**Comment by faddat** [comment]
sure-- ok let me explain this error:

1) it should have already gone away and if it hasn't please re-open this issue
2) this error happens because each account has a sequence starting with zero that goes up by one with each transaction, and it'll occur when the user of that account-- a relayer or your wallet-- submits a transaction with the incorrect account sequence. 
3) you have quite an account there sir-- unless this is for an ibc transaction?  Many of the relayers have sequence numbers like those and otherwise that is quite rare.

Thanks!  Please re-open this if it has not been resolved.
