### ISSUE TITLE
[x/gamm][Testing] Shuffling tests around to get more next to the AMM math code

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1407]

**Comment by p0mvn** [comment]
@ValarDragon , 

Created this issue from the epic in #1050 to make sure that we don't have non-issue bullet points.

Please fill in the description, labels, priority, and size when you have time

**Comment by p0mvn** [comment]
Need to bring stableswap structure closer to the balancer so that tests can be shared as well

**Comment by ValarDragon** [comment]
Is this outdated
Cc @AlpinYukseloglu

**Comment by AlpinYukseloglu** [comment]
Synced with @p0mvn offline about this –

Tldr is we agreed we should close this issue and revisit the topic of factoring out common gamm tests once we finish implementing stableswap tests (which are mostly unfinished right now and need more work in general since they were not prioritized during our gamm module audit)

This would also help us save time on implementing stableswap tests since we would not have to worry about exporting private functions across packages and, importantly, would prevent the case where we incorrectly assume a test can be generalized across balancer & stableswap and then have to waste time backtracking
