### ISSUE TITLE
DaoDao and contract deployment

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#1439]
Hi, I am working on a daodao deployment script here:

https://commonwealth.im/osmosis/discussion/4643-deploy-daodao

## concerns and questions
The first is the largest, about gov props.  I have a feeling that this can cause five of them:

* Daodao is at least five contracts.  Will that mean five governance proposals?
  * Daodao requires two external contracts:
    *  cw20 
    *  cw4
  * Daodao specific contracts:
    *  cw20-stake
    * cw3-multisig
    * cw-dao

* Do gov props occur at contract upload, or at contract instantiation?
  * Each dao is an instantiation of daodao
  * daodao is designed for limitless instantiation, does that mean limitless gov prop spam?

* CW20
  * This contract is very well understood and tested, and I would like to deploy it first.  My only real question here is weather or not this will conflict with plans for the token factory?

**Comment by ValarDragon** [comment]
cc @sunnya97, I believe alphaworks has a fork of the DaoDao contracts entirely working with native coins rather than cw20 which we can just directly use.

**Comment by faddat** [comment]
Nice, I will check that out.

Is there any reason you can think of that I should not pursue this deployment?

**Comment by ValarDragon** [comment]
Yeah, that deploying the contracts using the Alphaworks code with native SDK.Coins seems significantly preferrable

Please sync with them, my understanding is they are literally just waiting for review of their contract changes. They have a website made, and contracts done for a couple weeks AFAIU.

**Comment by faddat** [comment]
https://www.crunchbase.com/organization/alphaworks-867b

?


I guess the other thing would be to try to figure out how well we will be able to synchronize with the main line code base, I expect that daodao will become a standard in and of itself.


I would like to recount a narrative to you real quick:


So the other week somebody building out a block chain based public goods funding utility service contacted me for assistance with their CW contracts and after about a one hour long call and going through their different detail diagrams and plans we realized that every feature, 100%, of what they wanted was present in daodao already.

**Comment by ValarDragon** [comment]
Yeah, VMs are powerful abstraciton tools, and give much more rapid iterability! I totally agree.

I don't think that affects the choice of DaoDao vs Alphaworks' code (DaoDao but using native coins AFAIU)

One of the goals with our usage in Osmosis is to eliminate one of the core bug areas of Ethereum - different code paths for native coins and VM coins.

Solana did eliminate this, by having a special "Wrap sol" operation, and having everything deal with just contract layer code.

In our case, we want to expose the functionality needed for CW20 in a controller contract, but otherwise have all usages of CW20 instead be native coin backed, for iimproved interoperability with native code / other tooling. (And eliminating the need to operator over two coin types)

**Comment by faddat** [comment]
swoon
