### ISSUE TITLE
chore: auto-archive oldest issues in chain dev project

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1468]
**Context**

GitHub Projects (beta) have a limit of 1200 issues assigned to them.

We recently reached a limit: https://github.com/osmosis-labs/osmosis/runs/6378001010?check_suite_focus=true

To prevent this, we need to have a GitHub job that only keeps the latest 600 issues (this number can be changed as desired). For example, run on schedule every week and remove all issues from project that are older than 600 latest.

Our project: https://github.com/orgs/osmosis-labs/projects/1
View all unarchived completed issues: https://github.com/orgs/osmosis-labs/projects/1/views/48

**Acceptance Criteria**
- investigate and find an action to auto archive issues
- the github action works and archives the oldest issues

**Comment by daniel-farina** [comment]
We don't want to auto delete issues from the project, that would be a bad practice because then every time you are adding an issue the delete ones would show up again.

We need to archive them.

We need to figure out an action that deletes issues which are:
- closed
- merged
- older than 30 days

This should take care of things.

**Comment by p0mvn** [comment]
Unfortunately, such action does not seem to exist. https://docs.github.com/en/graphql/reference/mutations there is no exposed API to do anything like that either. As a result, I'm closing this for now
