### ISSUE TITLE
Support superfluid staking queries

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#1525]
## Background
cref: https://github.com/osmosis-labs/osmosis/pull/1191#issuecomment-1111114761

With superfluid module now being added governance support along with meeting the interface satisfaction, we should now try to integrate the staking query with the superfluid module if possible, if not try creating a conjoined query within the superfluid module  to have better support for querying superfluid staked assets.

## Suggested Design
Either both approach would suffice:
- make the existing staking query to support superfluid stakes assets as well
- Create a new query within the superfluid module
## Acceptance Criteria

> Goals & criteria for success
- being able to query staking information with superfluid staking integration

**Comment by nghuyenthevinh2000** [comment]
I explore both options and I think that the second options would be better. Here is why?

I first look at staking delegation query

1. By design, staking delegation query only returns one type of asset: 
https://github.com/cosmos/cosmos-sdk/blob/450cd7fc8708ccb0fa21f05e251d9804a2063b79/x/staking/keeper/querier.go#L464

Changing this would mean expanding staking query to return more assets.

2. Because of 1, I look at adding delegation query to superfluid. I try out on
"osmosisd q superfluid superfluid-delegation-by-delegator" first and it returns both superfluid delegation and staking delegation

![Screenshot from 2022-05-19 10-46-51](https://user-images.githubusercontent.com/23058164/169201176-062fd6df-5f92-4836-9f29-11cd141544af.png)

**Comment by nghuyenthevinh2000** [comment]
@mattverse @ValarDragon can you confirm my direction?

**Comment by mattverse** [comment]
@nghuyenthevinh2000 just left a review on the draft PR!

**Comment by nghuyenthevinh2000** [comment]
@mattverse @ValarDragon @alexanderbez 

I guess that it will be hard to decide, so I have combined @hieuvubk work on osmo equivalent to mine. This is contribution to @hieuvubk 

New logic will include calculating osmo equivalent of superfluid asset and add it to normal staking:

![Screenshot from 2022-06-03 12-55-37](https://user-images.githubusercontent.com/23058164/171795460-6acf6593-7eab-45ea-9baa-b6522bc5ada6.png)

**Comment by nghuyenthevinh2000** [comment]
@mattverse @ValarDragon @alexanderbez 

I guess that it will be hard to decide, so I have combined @hieuvubk work on osmo equivalent to mine. This is contribution to @hieuvubk 

New logic for delegation query will include calculating osmo equivalent of superfluid asset and add it to normal staking:
![Screenshot from 2022-06-03 12-55-37](https://user-images.githubusercontent.com/23058164/171795956-1eed729c-017f-4da2-b321-ca135ba3e7b5.png)
