### ISSUE TITLE
Post v9 ci chages

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#1695]
## Background

A while ago I made a CI system for Gaia that would do statesync in CI using all of the supported databases.

Here is an example of it running:

https://github.com/tendermint/tm-db/actions/runs/2439480213

## Suggested Design

I want to replicate this for osmosis v9 and begin to track rpc performance against live nodes in ci.

But this adds several jobs that will take over five minutes.

## Acceptance Criteria

Mainly want to get thoughts on this from @ValarDragon , @p0mvn , and @catShaark since I know they're engaged on performance work.

**Comment by p0mvn** [comment]
I think this is a great idea. We already have WIP to enable e2e state sync tests in:
- https://github.com/osmosis-labs/osmosis/pull/1613
- https://github.com/osmosis-labs/osmosis/pull/1572

Since e2e is state synching from a local testnet, it should be pretty quick (under 1-2 minutes). There is going to be no support for several db backends in the beginning but it would be very useful to add it in the future. I think we should definitely enhance e2e with support for rocks or other database that we are recommending

**Comment by p0mvn** [comment]
Is there anything that we can't do in e2e and only with live nodes?

If yes and having live nodes is desired, I think we could enable this job to run only on merge to `main` branch to avoid letting developers wait for pull request CI to pass

**Comment by p0mvn** [comment]
Hi @faddat . I'm going to close this issue since it has been stale for over a month. Please let me know if you would like to continue discussing anything here
