### ISSUE TITLE
Go module versioning

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#1709]
For reasons that I don't yet understand, we have moved the main branch back to v7.

This is making reviews and contributions a bit more complicated for me, and I just wanted to know why that was done

**Comment by hleb-albau** [comment]
can we use v9 for now?

**Comment by faddat** [comment]
@hleb-albau I don't know, that's actually the reason for this issue.  Just seeking guidance on how to use the module version paths currently.

**Comment by p0mvn** [comment]
I think it's time to do this. Our main branch is still on v7. What do others think? I can create a PR today if we are good with this

**Comment by p0mvn** [comment]
Sounds good, on it

**Comment by p0mvn** [comment]
The manual workflow is now in. However, the rest of the CI does not auto-run from the pull request triggered by the workflow (example #2096). The reason is a Github security limitation, ref: https://github.com/peter-evans/create-pull-request/issues/48

One of the manual solutions is to close and reopen a PR. There are more automatic solutions that are listed here: https://github.com/peter-evans/create-pull-request/issues/48

Unfortunately, the currently chosen Github Action [does not support any suggested automatic solutions](https://github.com/devops-infra/action-pull-request/blob/57505c3ec22b9b4c620137bd19341991be0d86f1/entrypoint.sh#L39). We would either have to fork the existing action and modify it or switch to: https://github.com/peter-evans/create-pull-request

I think closing and reopening to trigger CI is fine for the time being. This workflow is not meant to be run regularly anyways (only on major releases).

I'm still open to changing the action if it proves to be troublesome
