### ISSUE TITLE
Ensure multiplicative tolerance for share unit tests is as `actualShares <= expectedShares`

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#1733]
We should also ensure that `actualShares <= expectedShares` right?

_Originally posted by @ValarDragon in https://github.com/osmosis-labs/osmosis/pull/1731#discussion_r893878529_

**Comment by mattverse** [comment]
Yeah alot of the test cases get broken when we add `	require.LessOrEqual(t, actualShares, expectedShares)`

further investigating

**Comment by ValarDragon** [comment]
The existing situation should be safe. Spent awhile investigating this. First, details of the situation:
* PowApprox for exponents that != .5 has an insufficient accuracy threshold, 10^-8. This ends up translating to errors on the order of 10^-7 % - 10^-8% of total share amount in these tests.
* PowApprox is called in single asset join methods, and swaps
* This means they can all be off (in the positive direction) by 10^-7 to 10^-8
* This is fine, because in all cases they are used, the input is also charged swap fee, on the order of 10^-3. We just have to be extra careful this is the case in JoinPoolNoSwap.

My thought was then to do:
* Thus we amend the tests to special case the 0 swap fee to allow the positive error, and otherwise disallow positive error

however, that didn't work, as there is rounding error still, just you shouldn't be able to exit pool off of it to get more than the input due to the swap fee dominance. :sweat: 

best way to test this would be off the pool, shares pair on all the test vectors, or a new randomized test

**Comment by AlpinYukseloglu** [comment]
Hmm even though there's still a rounding error in the swap fee case, shouldn't the swap fee eclipse it and cause those tests to pass?

Or do you mean the no swap fee case still errors?

In any case, would it be too much to implement a minimum swap fee of 1e-7 (or just make it so a 0 swap fee effectively still takes a 1e-7 fee) to prevent a pool from outputting more than it takes in in any situation?

**Comment by ValarDragon** [comment]
I think we can close this, our current behavior is correct

In the swap fee case, we still could be greater than expected in the wolfram calculation test vector. But the point is that the error is tolerable due to the swap fee.

The Exit(Join(input)) < input invariant will hold due to swap fee, even with the roundup behavior.

We should increase the accuracy from 10**-7 generally though
