### ISSUE TITLE
Start making a test standards / template doc

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1954]
## Background

We should make a list in contributing.md's, of TDD that follow good standards that we can copy/paste from.

List of some good example tests we can copy/paste from:
- https://github.com/osmosis-labs/osmosis/blob/main/x/epochs/keeper/abci_test.go#L20
- https://github.com/osmosis-labs/osmosis/blob/main/x/tokenfactory/keeper/admins_test.go#L122
- {Roman to c/p} Gamm unit tests that are good

Eventually should abstract into go test templating tools #1444

**Comment by p0mvn** [comment]
- https://github.com/osmosis-labs/osmosis/blob/5be82920fa67a97c2c2dff1c06edd10e0ab66319/x/gamm/pool-models/balancer/pool_test.go#L423
  * I like how this one tests what kind of error has specifically occurred and not just presence/absence of an error
- https://github.com/osmosis-labs/osmosis/blob/5be82920fa67a97c2c2dff1c06edd10e0ab66319/x/gamm/pool-models/balancer/pool_test.go#L211
   * This is a complex example with the custom assertions -  `assertPoolStateNotModified` and `assertExpectedSharesErrRatio` but I think that  is acceptable due to the complex nature of the system being tested (requiring some custom assertion logic as a result of the complexity)
