### ISSUE TITLE
Make ice box for important backlog items

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#2066]
## Background

Ideally our backlog gets smaller each sprint. This requires us to have a place where we can properly table important backlog items and prioritize them properly. We agreed on call that an ice box would be an appropriate path for this.

## Suggested Design

- Create an ice box project on github and populate it with our backlog items on a future chain dev call

## Acceptance Criteria

- Ice box reflects our current backlog

**Comment by alexanderbez** [comment]
Created a new panel/tab in the existing osmosis project board along with a new label to filter issues by, `T:ice-box`, for which we should add to issues as we triage.

If the intent was to actually create a new project board, pleas let me know 👍

**Comment by alexanderbez** [comment]
https://github.com/orgs/osmosis-labs/projects/1/views/52

**Comment by p0mvn** [comment]
What do you think about using milestones for this? I've been playing around with them and looks like a good use case since milestones are meant for tracking long-lasting items across sprints:

There are 2 views:
- https://github.com/orgs/osmosis-labs/projects/1/views/50
   * across all milestones
- https://github.com/osmosis-labs/osmosis/milestone/1
   * per each milestone

**Comment by p0mvn** [comment]
Closing since no more thoughts on using this via milestones
