### ISSUE TITLE
Flat fees for IBC transactions

### ISSUE THREAD

**Issue by mturkia** [osmosis-labs/osmosis#2220]
## Background

IBC relayers are paying the gas price of the destination chain, and with the volume of Osmosis, relayer can perform thousands of transactions per day. The introduction of minimum gas fees that many validators have done to fight 0fee spam transactions, relayers face problem of choosing gas fees that will get included into block fast but does not end up costing too much. And this is very hard when validators have min gas prices varying a lot.

## Suggested Design

I suggest that we set a flat for IBC transactions, similar to what is done with arbitrage fees. This IBC fee can be set to 0 or small fee that still guarantees that IBC transactions are included into block rapidly. This would take the balancing/guessing game out of setting the relayer fees.

## Acceptance Criteria

- [ ] IBC transactions are accepted with flat fee

**Comment by ValarDragon** [comment]
Hey sorry this went without a reply for so long.

Theres an overarching issue of chain DOSability in this regard, IBC txs are actually the most computationally expensive per byte, due to the amount of signature verifications involved in their verification today.

I think what I'd like to do is have an adaptive fee market with a base fee, and have IBC txs perhaps get a small reduction in base fee they have to pay.

My suggested direction for this would be to get high level alignment on adaptive fee market design (and that we will likely need to trial and error a lot), and get that integrated. Then secondly, later-on consider "reduction" costs for things like relaying. TBH, I think focus on making the batch signature verification cheaper may be an easier time/utility tradeoff though.

WDYT?
