### ISSUE TITLE
Update Swagger

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#2233]
## Background
Currently swagger has been long out of date, the main reason for this is that the current scripts(make file and script file in charge of generating docs) has broken directory settings for swagger, thus has not been generating updated swagger files. This should get fixed so that the docs script updates swagger up-to-date and we have an updated version of swagger.yaml

## Acceptance Criteria

- [ ] Fix docs gen script so that it correctly generates updated swagger on `make docs` run.
- [ ] Have the swagger file up to date with the most recent proto

**Comment by ctrl-Felix** [comment]
I've looked into it and I also think I can provide a fix but there's another issue which comes first. Because of the ``docs`` folder make docs will return ``make: 'docs' is up to date.``

That means that either the make docs command needs to be renamed (generate-docs or compile-docs) or the docs folder needs to be renamed

**Comment by mattverse** [comment]
Awesome! Feel free to shoot up a PR whenever ready!

**Comment by ctrl-Felix** [comment]
Alright. PR is created!
