### ISSUE TITLE
Gather v12 QA items

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2444]
## Background

Lets have two people independently check the diff from main and v11.x and gather the list of state machine / client relevant files that have changed (e.g. what matters, not docs updates or e2e / simulator)

We should have two people do this for the redundancy aspect

Then we make a QA strategy off of these.

**Comment by czarcas7ic** [comment]
In trying to keep this list as succinct as possible, I am also going to exclude commits that ONLY change tests and does not change the logic itself. Lmk if you agree

**Comment by czarcas7ic** [comment]
This is what I got on a first pass. I can go into depth about what specifically we should be testing, but I though the first step was going through each file and find the PRs that changed important files in ways that potentially changes logic / would just be good to double check:

## Should Consider In QA

- [Set MaxAgeNumBlocks to v12 upgrade handler](https://github.com/osmosis-labs/osmosis/pull/2216)
- [Set commit timeout to two seconds](https://github.com/osmosis-labs/osmosis/pull/2057) 
- [Modified osmomath PowApprox to not allow a negative base](https://github.com/osmosis-labs/osmosis/pull/1965)
  - This panics when negative base occurs, should just check around where this is used 
- [Bech32IBC removed from partialOrd](https://github.com/osmosis-labs/osmosis/pull/1994)
  - Shouldnt we add twap to this?
- [Adds MsgSetDenomMetadata to tokenfactory](https://github.com/osmosis-labs/osmosis/pull/2223)
- [Adds admin denom to tokenfactory wasm binding](https://github.com/osmosis-labs/osmosis/pull/1645)
- [Twap wasm bindings](https://github.com/osmosis-labs/osmosis/pull/2212)
- [Removed legacy sdk.Msg handlers](https://github.com/osmosis-labs/osmosis/pull/1996)
  - Maybe just double check this PR as a whole 
- [Proto gen changes](https://github.com/osmosis-labs/osmosis/pull/1589)
  - Saw some changes in epochs/types/query.pb.gw.go that caught my eye
- [GetNextPoolID vs GetNextPoolNumberAndIncrement vs getNextPoolIdAndIncrement](https://github.com/osmosis-labs/osmosis/pull/2160)
- [Add check for correct input asset denoms to CalcJoinPoolShares](https://github.com/osmosis-labs/osmosis/pull/1931)
- [Stableswap make sure only join by assets that already exist in pool. Also after joining pool, ensures tokens length does not change](https://github.com/osmosis-labs/osmosis/pull/2301)
- [Add scaling factors to stableswap pool creation](https://github.com/osmosis-labs/osmosis/pull/2222)
- [Amino serialization for Authz](https://github.com/osmosis-labs/osmosis/pull/2206)
- [Add fixed gas cost for swaps](https://github.com/osmosis-labs/osmosis/pull/2016)
- [Incentives CLI fix rewards-estimation](https://github.com/osmosis-labs/osmosis/pull/1985)
- [Changes getToDistributeCoinsFromGauges so that it only iterate through all gauges once](https://github.com/osmosis-labs/osmosis/pull/2014)
- [Adds an invariant to ensure that the module balance and the sum of all tokens within all locks have the equivalent amount of tokens](https://github.com/osmosis-labs/osmosis/pull/1884)
- [Refactor AddToExistingLock](https://github.com/osmosis-labs/osmosis/pull/1979)
- [check coins are positive in lockup ValidateBasic](https://github.com/osmosis-labs/osmosis/pull/2180)
- [Further validate basics for lockup](https://github.com/osmosis-labs/osmosis/pull/2205)
- [FundCommunityPoolFromModule in the pool-incentives module calls FundCommunityPool in the Cosmos SDK now](https://github.com/osmosis-labs/osmosis/pull/1909)
- Superfluid adds GetCmdTotalDelegationByDelegator

## Integrator Notes
- [Moved from camelCase to snake_case for protobuf](https://github.com/osmosis-labs/osmosis/pull/1656)
- [Added share_out_amount and token_in to MsgJoinPoolResponse, token_out to MsgExitPoolResponse, and JoinPoolNoSwap returns `tokenIn sdk.Coins, sharesOut sdk.Int`](https://github.com/osmosis-labs/osmosis/pull/1886)
- [QueryGaugeIdsResponse now shows % of incentives going to that gauge ID](https://github.com/osmosis-labs/osmosis/pull/1815)

## Random Stuff
- Twap as a whole should be tested
- x/epochs/keeper/keeper.go, why do we still require cdc in NewKeeper?
- Removed errors.go for epoch module, assume its desired just pointing it out
- Removed MaximalExactRatioJoinBroken in x/gamm/pool-models/internal/cfmm_common/lp.go, also assume its desired I just didn't know the context for it

**Comment by ValarDragon** [comment]
- [ ] osmomath/math.go (adding base is negative check), sanity check this should never happen
- [ ] gamm proto fields being made to be snake case instead of camel case. (Need to figure out how to make this not an ecosystem break)
- [ ] Review gamm proto message responses (were they done correctly / as you'd expect?)
- [ ] proto/superfluid - check if we deleted some queries? Unclear to me on quick skim
- [ ] TokenFactory setDenomMetadata message. I remain worried about unclarity around bank registry, I think we just setup another registry for display data.
- [ ] TWAP
- [ ] Review wasmbinding differences
{app/wasm => wasmbinding}/README.md                                                 |    6 +-
 {app/wasm => wasmbinding}/bindings/msg.go                                           |    2 +-
 {app/wasm => wasmbinding}/bindings/pool.go                                          |    2 +-
 {app/wasm => wasmbinding}/bindings/query.go                                         |   44 +-
 {app/wasm => wasmbinding}/bindings/types.go                                         |    2 +-
 {app/wasm => wasmbinding}/bindings/types_test.go                                    |    2 +-
 {app/wasm => wasmbinding}/message_plugin.go                                         |   42 +-
- [ ] x/epochs difference - https://github.com/osmosis-labs/osmosis/blob/main/x/epochs/keeper/abci.go#L19-L21
- [ ] x/gamm
  - [ ] What happened to the README?
  - [ ] Sanity check that messages still work, as we deleted the handler and now use Stargate handling for messages
    - Double check if we have go tests based on msg / tx execution
  - [ ] review ctx.GasMeter().ConsumeGas(types.BalancerGasFeeForSwap, "balancer swap computation")
  - [ ] https://github.com/osmosis-labs/osmosis/blob/main/x/gamm/pool-models/balancer/pool.go#L692-L698
  - [ ] Double check stableswap messages are still disabled
- [ ] x/incentives
  - [ ] TODO
- [ ] x/lockup
  - [ ] TODO
- [ ] x/pool-incentives
  - [ ] TODO
- [ ] x/superfluid
  - [ ] TODO
- [ ] x/tokenfactory
  - [ ] TODO
- [ ] x/TWAP
  - [ ] Review logic
  - [ ] Review safety of all external module calls & arithmetic (no panics should be possible in beginblock/endblock)
- [ ] x/txfees
  - [ ] TODO
- [ ] Cosmwasm stargate queries
- [ ] Tests for items in v12 upgrade handler

**Comment by czarcas7ic** [comment]
Write single tracker issue of items people can test indv

**Comment by p0mvn** [comment]
Requesting one more review on this SDK PR please if anyone has time: https://github.com/osmosis-labs/cosmos-sdk/pull/265

**Comment by p0mvn** [comment]
This can now be closed

**Comment by alexanderbez** [comment]
Woohooo nice work team!
