### ISSUE TITLE
TWAP: Ensure that pruning does not prune the last record

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2518]
## Background

With TWAP Record pruning, we should adjust the implementation, so that it preserves one record past the pruning period.
The reason for this can be seen below.
* Suppose pruning param -48 hour
* Suppose swaps at -50 hour, -1hour
* A prune would leave us with only record at -1 hour, and we would not be able to get twaps from the [-48 hour, -1 hour] time range.

## Suggested Design / Acceptance Criteria

- [ ] TWAP pruning will preserve the newest record past -48 hour, if any records past -48 hours exist.
- [ ] Testing this

**Comment by p0mvn** [comment]
Something I've been thinking about:

Let's assume that the pruning param is 48 hours like in the example.

Suppose we implemented a change like suggested. Now, we have a record at - 50 hours and -2 hours.

Technically, the API now allows getting records before parameterized -48 hours. We can also have -49 or -50 since the earliest available record is at -50.

It seems that now we cannot define the earliest available twap deterministically. The newest record before -48 hours could be at any time.

I think it might make sense to add the following check:
```
func (k Keeper) GetArithmeticTwapToNow(
	ctx sdk.Context,
	poolId uint64,
	baseAssetDenom string,
	quoteAssetDenom string,
	startTime time.Time) (sdk.Dec, error) {
	time := ctx.BlockTime()
	keepPeriod := k.GetParams(ctx).RecordHistoryKeepPeriod
	if startTime.Before(time.Add(-keepPeriod)) {
		return sdk.Dec{}, fmt.Errorf("called GetArithmeticTwapToNow with a start time (%d) that is earlier than"+
			"current block time (%d) - keep period (%d)", startTime, time, keepPeriod)
	}

```

That would limit the earliest available twap to the `block time - keep period` despite the possibility of having an earlier record.

**Comment by ValarDragon** [comment]
Why is it an issue to serve an earlier record if we have it, as long as API callers know that its not guaranteed to exist?

**Comment by p0mvn** [comment]
There isn't a specific issue preventing us from doing that. It just felt odd having the variability in the threshold of when twaps can be available. As a result, I was thinking of providing more specific guarantees. 

If you think this is fine, I will implement it in a way that does not guarantee that a record exists before the keep threshold. However, if it does, the twap before the keep threshold is valid.
