### ISSUE TITLE
Make a file-based way to update pool incentives

### ISSUE THREAD

**Issue by sunnya97** [osmosis-labs/osmosis#267]
Currently, EditPoolIncentives proposals have to be done via the CLI using command line arguments.  There should be a way to easily put the records in a file and just pass in a file to the CLI.  (similar to gamm's create-pool)

**Comment by xBalbinus** [comment]
Does https://github.com/osmosis-labs/osmosis/issues/368 close ^ or no?

**Comment by xBalbinus** [comment]
I think at least currently, pool-incentives related proposals can be done via. a yml file (at least with beaker)

**Comment by p0mvn** [comment]
I briefly looked into this:
https://github.com/osmosis-labs/osmosis/blob/fe98f6e4453cd32035d277c21ef2f3669b677bb2/osmoutils/parse.go#L61

I don't see a way to parse a yml file, only json.

I think the goal of this issue is to make it possible to utilize yml format via CLI like beaker does.

I suspect that beaker has custom logic for parsing yml files that's why it works. cc: @iboss-ptk is that the case?

**Comment by iboss-ptk** [comment]
@p0mvn yes, it's [this struct](https://github.com/osmosis-labs/beaker/blob/main/packages/cli/src/modules/wasm/proposal/proposal_struct.rs#L30) which, [when the file has `yaml` or `yml` extension, it gets deserialized to the said struct](https://github.com/osmosis-labs/beaker/blob/213f82c34adb70ae2e08703a3943b3369d307c3a/packages/cli/src/modules/wasm/proposal/entrypoint.rs#L79).

**Comment by ValarDragon** [comment]
Closing due to obsolete
