### ISSUE TITLE
ci: adjust mergify Automerge label to merge when CI passes and >= 2 approvals

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#2747]
## Background

Currently, "A:Automerge" label merges when CI is still in-progress and might fail. Additionally, it only requires 1 approval.

## Suggested Design

Follow the instructions in https://docs.mergify.com/conditions/#about-status-checks to add status checks for tests and lint jobs:
https://github.com/osmosis-labs/osmosis/blob/38419628d8bbfadf55be32ff622e59a398c28915/.github/mergify.yml#L13-L17

Change approved reviews from 1 to 2.

## Additional Context

I've run into issues trying to match our CI job names while testing the approach for "check-success". It would be useful for the person working on this to have access to the mergify dashboard to debug.

## Acceptance Criteria
- suggested changes implemented
- tested that the changes work on a personal fork

**Comment by MasterPi-2124** [comment]
Hi, I am working on this, but I can't set up a mergify test for it in the forked repo. I have to add name jobs individually because mergify doesn't allow checking multiple statuses with just one condition. We also need to change the setting in the "branch protection rules" section and modify mergify file as I suggested: https://github.com/notional-labs/osmosis/blob/main/.github/mergify.yml

this is my testing pull request that I am working on: https://github.com/notional-labs/osmosis/pull/71
