### ISSUE TITLE
Export State with Order Metadata

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#2955]
## Background

Currently, when exporting mainnet state, we do not export any kind of order metadata. When calculating the app hash by hashing the module hashes, this order matters.

## Suggested Design

* Export order metadata so we are constructing the Merkle tree in the same way we are on mainnet

## Acceptance Criteria

TBD

**Comment by hieuvubk** [comment]
Is this about the order of modules when exporting? Currently `OrderExportGenesis` not be set, so when exporting state returns the modules in alphabetical order.
I don't know if the current way is correct for the Merkle tree we are using. So pls lmk what u think

**Comment by ValarDragon** [comment]
We can't state export such that we can reconstruct the same tree unfortunately, based on how "state export" is defined in cosmos-land. This is because state depends on the tree structure of IAVL, which itself depends on insertion order.

So state sync snapshots do this, and we can maybe create some way to apply modifications onto a state sync snapshot, which is a true "state export", unlike what we typically do.

**Comment by ValarDragon** [comment]
No longer needed with in-place state modification tooling
