### ISSUE TITLE
Spending too much gas on accumulationStore by denom as time goes

### ISSUE THREAD

**Issue by antstalepresh** [osmosis-labs/osmosis#337]
Code to debug gas consume

```go
	fmt.Println("step2", ctx.GasMeter().GasConsumed()-lastSpent)
	lastSpent = ctx.GasMeter().GasConsumed()
	for _, coin := range lock.Coins {
		k.accumulationStore(ctx, coin.Denom).Set(accumulationKey(lock.Duration, lock.ID), coin.Amount)
	}

	fmt.Println("step3", ctx.GasMeter().GasConsumed()-lastSpent)
	lastSpent = ctx.GasMeter().GasConsumed()
```

```go

func (suite *KeeperTestSuite) TestLockTokensAlot() {
	addr1 := sdk.AccAddress([]byte("addr1---------------"))
	coins := sdk.Coins{sdk.NewInt64Coin("stake", 10)}
	skipLogsFor := 9000
	for i := 0; i < skipLogsFor; i++ {
		// addr1 := sdk.AccAddress(secp256k1.GenPrivKey().PubKey().Address())
		suite.LockTokens(addr1, coins, time.Second)
	}
	for i := 0; i < 1000; i++ {
		alreadySpent := suite.ctx.GasMeter().GasConsumed()
		// addr1 := sdk.AccAddress(secp256k1.GenPrivKey().PubKey().Address())
		suite.LockTokens(addr1, coins, time.Second)
		newSpent := suite.ctx.GasMeter().GasConsumed()
		spentNow := newSpent - alreadySpent
		fmt.Println("sum up - consumed gas", i+skipLogsFor, spentNow)
	}
	panic(1)
}

```

Log
```
step1 17071
step2 25920
step3 343617
sum up - consumed gas 9999 391082
```

When user lock tokens 10000 times, his/her gas spending for locking tokens take around 400K, it's quite large and we definitely need to reduce it.

**Comment by mconcat** [comment]
Which branch is this debug code is on?

**Comment by mconcat** [comment]
```go
func (node *node) children() (res children) {
   bz := node.tree.store.Get(node.tree.nodeKey(node.level, node.key))
   if bz != nil {
     json.Unmarshal(bz, &res)
   }
   return
 }

 func (node *node) set(children children) {
   bz, err := json.Marshal(children)
   if err != nil {
     panic(err)
   }
   node.tree.store.Set(node.tree.nodeKey(node.level, node.key), bz)
 }
```

acc store uses json internally and this might be a problem

**Comment by antstalepresh** [comment]
> Which branch is this debug code is on?

https://github.com/osmosis-labs/osmosis/pull/336

**Comment by mconcat** [comment]
Moving to protobuf reduces around 60% of the gas cost, however, the main problem on the gas consumption looks like the redundant update on the children. I used the children size per node `m=10`, which makes a large size of writing operation = high gas cost. I'll try multiple selections of the constant `m` to find out which is the most efficient one.

**Comment by mconcat** [comment]
test condition: 100 locks average gas consumption after 5000 skiplogs
- m=4: 212205
- m=5: 221630
- m=6: 183883
- m=7: 190484
- m=8: 174843
- m=9: 176548
- m=10: 172368
Turns out that was not the problem.

**Comment by ValarDragon** [comment]
After all the work in the accumulation store, this should have been significantly mitigated. Using the benchmark of #442 with `10000` locks, and averaging after `5000` of them, I got:

```
test deets: begin average at 5000 total locks created 10000
average: 177891
max gas / lock: 312705
```

Assuming Eugen's numbers for `step 1` and `step 2` are constant (would need to check), this implies that the accumulation store is taking around 130k gas on main on average, which is really reasonable! Theres probably some I/O reads that can be optimized, but that certainly seems like diminishing returns imo, especially in the face of options to just reduce the number of locks there are.

The worst case behavior isn't great (but _much_ better than before). We probably eventually need to do a bit of thinking around worst case behaviour, and potentially lowering reads/write amounts in the future, but for now I think it is fine. We may have to visit this in terms of just figuring out how much gas to be using front-end side though, so users don't get random tx fails due to out of gas.

We should close this issue after we make an issue to investigate if theres I/O performance opportunities. (Though I think we should let external contributors try to tackle this one or our future selves when this becomes more problematic, while we focus more on our core innovations)

**Comment by ValarDragon** [comment]
Very much fixed in main, with a variety of problems underneath in the SDK resolved

**Comment by ValarDragon** [comment]
After joon's PR for making everything with the same duration use the same leaf, its now:
```
test deets: total locks created 10000, begin average at 1000
average gas / lock: 64027
max gas / lock: 64028
```
