### ISSUE TITLE
test(stableswap): compare direct solver and binary search solver outputs given the same inputs

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3438]
## Background

We should have a test comparing the results of the direct solver to the binary search solver. That is,

- [solveCFMMMultiDirect](https://github.com/osmosis-labs/osmosis/blob/6398733549c124cb973eaa20d7aaba0fe6915ab9/x/gamm/pool-models/stableswap/amm.go#L178)
- [`solveCFMMBinarySearchMulti`](https://github.com/osmosis-labs/osmosis/blob/6398733549c124cb973eaa20d7aaba0fe6915ab9/x/gamm/pool-models/stableswap/amm.go#L314)

## Suggested Design

Create a table-driven test with hand-picked values. Call both functions and compare the results

## Acceptance Criteria
- make sure that there is no difference or that the difference is within the acceptable bounds

**Comment by p0mvn** [comment]
@AlpinYukseloglu let me know what you think, please. I think this would be nice to have before the upgrade

**Comment by AlpinYukseloglu** [comment]
We actually did have a test like this but ended up splitting it up into separate ones - since we test both the direct and binary search solvers against the same CFMM (i.e. k stays constant for both), adding this back in wouldn't meaningfully increase coverage imo. I'll still try to throw one together if I get through the rest of my pre-launch backlog but this shouldn't be release blocking imo
