### ISSUE TITLE
[CL]: Positions - Have updatePosition take Pool instead of PoolID

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#3623]
## Background

See https://github.com/osmosis-labs/osmosis/blob/244b28a450d3e64c24d2c8a71c4fe56cf7865348/x/concentrated-liquidity/lp.go#L40-L55

And https://github.com/osmosis-labs/osmosis/pull/3607/files#r1038803281

## Suggested Design

We should have the updatePosition function take a pool object instead of a poolID, so we dont have to call setPool within the createInitialPosition function

## Acceptance Criteria

TBD

**Comment by czarcas7ic** [comment]
@p0mvn I actually don't quite see why this would be desirable. Lets be sure to discuss this issue in the next CL meeting

**Comment by p0mvn** [comment]
In both callers of `updatePosition` we have access to the pool itself:

1. `createPosition`: https://github.com/osmosis-labs/osmosis/blob/244b28a450d3e64c24d2c8a71c4fe56cf7865348/x/concentrated-liquidity/lp.go#L35
2. `withdrawPosition`: https://github.com/osmosis-labs/osmosis/blob/244b28a450d3e64c24d2c8a71c4fe56cf7865348/x/concentrated-liquidity/lp.go#L116

Still, we end up taking only a pool id in `updatePosition` and then re-getting the pool from id: https://github.com/osmosis-labs/osmosis/blob/244b28a450d3e64c24d2c8a71c4fe56cf7865348/x/concentrated-liquidity/lp.go#L159-L162

That "re-get" seems redundant since `updatePosition` could take the pool directly as a parameter

**Comment by p0mvn** [comment]
FYI @czarcas7ic unassigning since I don't think you're working on this. Please correct me if I'm wrong

**Comment by mattverse** [comment]
@czarcas7ic @p0mvn  aren't pools mutable? Im afraid that passing around a mutable object via parameter can cause higher security vulnerability. (if not, agreed with the notion of this issue)

**Comment by czarcas7ic** [comment]
I looked into this again today and still don't feel like its worth passing around a mutable pool. Especially in the future, if we add logic and need to re-retrieve the pool before calling updatePool and forget to do so, we would introduce a bug. I guess what I am saying is, there is very little positive that can come from making this change (reduce a little code duplication and maybe reduce a little overhead) but very large negative that could eventually be introduced.

**Comment by p0mvn** [comment]
> I looked into this again today and still don't feel like its worth passing around a mutable pool. Especially in the future, if we add logic and need to re-retrieve the pool before calling updatePool and forget to do so, we would introduce a bug. I guess what I am saying is, there is very little positive that can come from making this change (reduce a little code duplication and maybe reduce a little overhead) but very large negative that could eventually be introduced.

I disagree and don't understand the negatives described.

The purpose of this method is to mutate a pool and write it to state. When this is the goal, I don't understand the concern about mutations. If we pass a wrong pool id to this method, it will still mutate the pool with that id.

> Especially in the future, if we add logic and need to re-retrieve the pool before calling updatePool and forget to do so, we would introduce a bug

If we require to pass in the pool, we need to retrieve it always prior to calling the method.

There is a problem today where you can get a pool before calling `updatePool`. Then, call `updatePool` on the pool with that id but continue to operate on the old pool struct from the caller.

I don't feel strongly about this change though so let's close this issue if my last comment doesn't convince you otherwise

**Comment by czarcas7ic** [comment]
I guess my main point is, you agree that we MUST retrieve the pool directly before calling updatePool, in the event that the pool object has been mutated prior to the call. So if we must retrieve it again before calling updatePool, we might as well call it within updatePool itself so we never forget to do the above.

**Comment by p0mvn** [comment]
Going to work on this change since not having it just caused a hidden bug in incentives claiming where one of the internal methods would mutate the pool and write it to state but another level at a higher level of abstraction would operate on an outdated copy of the pool and then end up overwriting the state with an out-of-date copy.

**Comment by p0mvn** [comment]
Ended up going with a simpler fix to save time
