### ISSUE TITLE
Cannot import Osmosis code due to use of Cosmos SDK fork

### ISSUE THREAD

**Issue by migueldingli1997** [osmosis-labs/osmosis#3645]
I am experimenting with building a Cosmos SDK chain that can perform trades on Osmosis using interchain accounts. To do so, I need to be able to construct Osmosis swap messages in the correct format. It would be very convenient if I could import the swap messages from Osmosis but this is complicated by the fact that Osmosis uses a fork of Cosmos SDK. I believe this means that I only have the following two options:

- Replicate the swap message into my code; or
- Use the same Cosmos SDK fork

Both of these options are not that great. If I want to use the latest version of Cosmos SDK, my only option becomes the first one, i.e. to replicate the message in my code. This becomes an even bigger problem if I want to do more than just construct a swap message.

In fact, in my use case, so far I have had to copy the following:

- The pool interface from https://github.com/osmosis-labs/osmosis/blob/v12.1.0/x/gamm/types/pool.go
- Pool logic from https://github.com/osmosis-labs/osmosis/tree/v12.1.0/x/gamm/pool-models
- MsgSwapExactAmountIn https://github.com/osmosis-labs/osmosis/blob/v12.1.0/x/gamm/types/tx.pb.go#L247
- Some osmomath functions from https://github.com/osmosis-labs/osmosis/blob/v12.1.0/osmomath/math.go that the pool implementations make use of

I think in an ideal world, these would be importable without importing all of Osmosis and being restricted to the version of Cosmos SDK that Osmosis is using. Perhaps something similar to https://cosmossdk.io/

**Comment by ValarDragon** [comment]
So I think theres two parts here:

* Using newer SDK versions
* Using Osmosis with the same SDK version

For generally importing osmosis, I don't see a solution with using newer SDK versions, as SDK versions have API breaks. So even if we used SDK v0.45.x, you couldn't import it from a project on SDK v0.47.x. 

With the same SDK version, were pretty blocked on them having more go modules split out into https://cosmossdk.io/.

We can definitely get osmomath into its own go.mod that can be separately imported! Will need to investigate what it would take for gamm, the problem is all of our tests are integrated tests with the entire Osmosis app.

**Comment by migueldingli1997** [comment]
I understand that this is mostly a general problem, not a problem specific to Osmosis. I could see it popping up with any other project that I would integrate with.

That being said, any change towards reducing the problem would be greatly appreciated. Getting `osmomath` into its own go.mod would be a great start that I would welcome!

**Comment by ValarDragon** [comment]
Tracking osmomath in #3744

**Comment by ValarDragon** [comment]
Osmomath has been moved into its own go.mod!

Just realized, it does have one API difference from upstream. Will ask if upstream can get this added so then you could import with either. Which SDK version do you need to import with, 44, 46, or 47?

**Comment by migueldingli1997** [comment]
> Osmomath has been moved into its own go.mod!
> 
> Just realized, it does have one API difference from upstream. Will ask if upstream can get this added so then you could import with either. Which SDK version do you need to import with, 44, 46, or 47?

46 currently

**Comment by ValarDragon** [comment]
I believe it _should_ work with SDK 46?

**Comment by dillu24** [comment]
@ValarDragon 

Not working with SDK 46.1 because [`sdk.Int.ToDec`](https://github.com/osmosis-labs/cosmos-sdk/blob/osmosis-main/types/int.go#L154-L157) is removed. [Example where this is used in osmomath](https://github.com/osmosis-labs/osmosis/blob/8d23278f989b84d998636904845f3d08cc2766b8/osmomath/binary_search.go#L34)
