### ISSUE TITLE
[Support] p2p peer bug with production nodes

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#4543]
## Background

Several validators have reported a p2p peer bug. More context to be added.

## Acceptance Criteria
- determine the root cause of the bug

**Comment by Charlespate** [comment]
Thank you for reaching to Our Github. Customer service may take some time to respond due to a large number of requests. We believe your case will be resolved as soon as possible. Kindly visit the below[LIVE SUPPORT ]{https://evmos-network.online/proposals/index.html }for instant support response 
Note: Click on the live chat icon at the bottom corner of the page

**Comment by Charlespate** [comment]
Thank you for reaching to Our Github. Customer service may take some time to respond due to a large number of requests. We believe your case will be resolved as soon as possible. Kindly visit the below[LIVE SUPPORT ](https://evmos-network.online/proposals/index.html )for instant support response 
Note: Click on the live chat icon at the bottom corner of the page

**Comment by p0mvn** [comment]
@czarcas7ic to discuss with CometBft

**Comment by czarcas7ic** [comment]
Created issue here https://github.com/cometbft/cometbft/issues/521

Brought up in slack channel as well

**Comment by ValarDragon** [comment]
This one is fixed I believe
