### ISSUE TITLE
fix: `CalcAmount0Delta` `Quo` -> `QuoTruncate`

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#4646]
## Background

We should investigate if we need to truncate at precision end when `roundUp` in `math.CalcAmount0Delta` is false

## Suggested Design

Investigate this: https://github.com/osmosis-labs/osmosis/blob/7223b8b6ca5e5e3b6a17592935e72f82a910968c/x/concentrated-liquidity/internal/math/math.go#L72

## Acceptance Criteria
- if that should be a `QuoTruncate`, apply the change and fix tests

**Comment by czarcas7ic** [comment]
Hey! I did some investigating into this and the conclusion I made was this was not needed for the following reason:

In CalcAmount0Delta, we determine the denom by multiplying sqrtPriceA and sqrtPriceB. 

https://github.com/osmosis-labs/osmosis/blob/3767fa15b2c3f44bec75a44877c6a0935e5f6df4/x/concentrated-liquidity/internal/math/math.go#L61

This multiplication will only ever round the denom up, therefore only ever making the final value lower (even without truncating)

This means that QuoTruncate is not required.

The way I came to the above conclusion, is I created two test cases.

```
		"rounding check, round up false": {
			liquidity:       sdk.MustNewDecFromStr("1517882923.648669463472052100"),
			sqrtPCurrent:    sdk.MustNewDecFromStr("70.710678118654752440"), // 5000
			sqrtPUpper:      sdk.MustNewDecFromStr("74.161984870956629487"), // 5500
			round:           false,
			amount0Expected: "998976.999999999999999999",
		},
		"rounding check, round up true": {
			liquidity:       sdk.MustNewDecFromStr("1517882923.648669463472052100"),
			sqrtPCurrent:    sdk.MustNewDecFromStr("70.710678118654752440"), // 5000
			sqrtPUpper:      sdk.MustNewDecFromStr("74.161984870956629487"), // 5500
			round:           true,
			amount0Expected: "998977.000000000000000000",
		},
```

The intent was to find a liquidity value that resulted in an amount0 that was on the edge of the next integer value. 

While the "rounding check, round up false" test case should have resulted in the amount0Expected shown in the test case, it actually resulted in a value of "998976.999999999999999989". 

When breaking down each part of the equation, I saw that the denom being calculated was "5244.044240850757734943" instead of "5244.044240850757734942", which will always result in a smaller than actual value in the non roundUp branch.

If there is agreement with the above logic, then I will submit a PR that removes the in line comment saying to address this, and close this issue.

**Comment by p0mvn** [comment]
> This multiplication will only ever round the denom up,

I don't understand this claim. Regular `Mul` multiplication does banker's rounding. I think we might even want to do `MulTruncate` and `QuoTruncate` in that case for deterministic truncation.

The reason why it was `"5244.044240850757734943"` was probably because the next decimal was greater than 5. e.g. `"5244.0442408507577349436"`. In that case, banker's rounding would round up. However, if it were` "5244.0442408507577349434"`, it would round down
