### ISSUE TITLE
Investigate GAMM CLI not working

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#500]
Oddly over the weekend we discovered that several GAMM CLI commands (namely JoinPool, and JoinPoolSwapExternAmountIn) that used to work, broke, giving the error 

```
Error: rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: token amount is zero or negative: invalid calculated result: invalid request
```

However the proto messages created by the old commands worked perfectly fine when re-signed and broadcasted. So the state machine didnt have any break.

This is odd, as theres nothing that looks like it will have broke it in v4 or v3.

**Comment by ValarDragon** [comment]
Oh wow 😕

Maybe something broke in join-pool to require two `max-amounts-in`?  e.g. this used to work per dimi
```
osmosisd tx gamm join-pool --pool-id 1 --max-amounts-in 1024943uosmo --pool-id 1 --share-amount-out 10290368762116767072 --from mykey --gas auto --gas-adjustment 1.4
```

If so, we should make make `max-amounts-in` do the sane thing and take in a list lol

**Comment by UnityChaos** [comment]
hmm.... I don't think that changed... like the proto values and the keeper functions for `join-pool` all require a `sdk.coins` arg for max-amounts-in. Like it should work to do `--max-amounts-in="1234ibc/xyz,5678ibc/abc"` using comma separated values. I just did them separately because I knew that would work
