### ISSUE TITLE
Difficulty Running Osmosis

### ISSUE THREAD

**Issue by nkrsic** [osmosis-labs/osmosis#519]
I am trying to install the daemon and run a node, using branch `v4.x`

I am able to install and init the moniker, but I am getting this error when I run `osmosisd start`

`7:30PM INF running initialization for module module=epochs
panic: unknown field "current_epoch_ended" in types.EpochInfo
`

When I look at the actual EpochInfo type in `x/epochs/types/genesis.pb.go` on line 31 I see that it does not have the field mentioned.

**Comment by nkrsic** [comment]
In the Discord here: 

https://discord.com/channels/798583171548840026/877743338760069141/891380625687322715

I was able to find advice here suggesting that the when not using state sync, the previous version 3.1 should be synced until the upgrade block (1314500), then switch to v4.

**Comment by ValarDragon** [comment]
Yeah, you can't use the v4 binary against genesis, and you can't use the genesis binaries against latest state :/

Unfortunately this is the confusion with syncing from genesis, hopefully we get more tooling to fix things / help protect against syncing with the wrong version.

You can use the chainlayer snapshots to relatively quickly get a snapshot of a recent block height, and run the mainnet binary off of that to get synced to the network: https://quicksync.io/networks/osmosis.html

I think we'll have to brainstorm in the SDK for a better way to give a user error when using too new of a binary against mainnet. Its a bit easier tbh to detect using too old of a binary, which has someone working on an improved error message there:

**Comment by ValarDragon** [comment]
> Maybe we need to ship a binary with cosmovisor and all the version binaries preinstalled?

I've been thinking of something more along jacob's idea, of one stop setup scripts. I'm thinking the end state here is something like rust-up, where it has you pick from a couple compiler options, with a default. 
Default:
* Pruned full node
* Use chainlayer to download it
Option axes:
* pruned node, store all old events or archive node
* Chainlayer, statesync, or fast sync
* If fast sync: start from genesis, or block N

> @sunnya97 - If it's for the sake of making it easier for newbies to be able to set this stuff up pretty easily, updating the docker image might be a great way to go. I tried using the compose file that was in the repo initially and it ended up failing because the image is no longer available on docker hub.

Thats a great idea. We have not touched the docker image, would love for someone to do that / to help support folks in doing it.

**Comment by dualsystems** [comment]
I get that error because genesis started with version 3  and upgraded to v4 ?

`1:21AM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
1:21AM INF Discovered new snapshot format=1 hash="$�\x0fĉx��.k�������N��o��$�T\x1f\x17��X�" height=1098000 module=statesync
1:21AM INF Discovered new snapshot format=1 hash="�L\x0f��\x00���7o���2��\x0f&&�X�\"��fI��d�" height=1096500 module=statesync
1:21AM INF new bucket is full, expiring new book=/data/.osmosisd/config/addrbook.json module=p2p
1:21AM INF new bucket is full, expiring new book=/data/.osmosisd/config/addrbook.json module=p2p
1:21AM INF Applied snapshot chunk to ABCI app chunk=33 format=1 height=2112000 module=statesync total=37
1:21AM INF Applied snapshot chunk to ABCI app chunk=34 format=1 height=2112000 module=statesync total=37
1:21AM INF Applied snapshot chunk to ABCI app chunk=35 format=1 height=2112000 module=statesync total=37
1:21AM INF Applied snapshot chunk to ABCI app chunk=36 format=1 height=2112000 module=statesync total=37
1:21AM INF Verified ABCI app appHash="3���¹�z��*�����ZO��\x04�m*����\\�d�" height=2112000 module=statesync
1:21AM INF Snapshot restored format=1 hash="k}\u007f��u\n�p/h�18\x0e��o[bw����\v.i����" height=2112000 module=statesync
1:21AM INF scheduler: run module=blockchain
1:21AM INF processor: run module=blockchain
panic: failed to process committed block (2112001:959110462FDE439320E8427039ECFF830C60A6F03C785520671515F8D8C30AE9): wrong Block.Header.Version. Expected {11 0}, got {11 1} [recovered]
        panic: failed to process committed block (2112001:959110462FDE439320E8427039ECFF830C60A6F03C785520671515F8D8C30AE9): wrong Block.Header.Version. Expected {11 0}, got {11 1}
last events:
0: scBlockReceived{2112001#959110462FDE439320E8427039ECFF830C60A6F03C785520671515F8D8C30AE9 from 727da24c1934ab28aff3156efac798ff20885d7e}
1: scBlockReceived{2112002#87440F228F7E0ACBDB336FBAEC5245C9B6A6DF8AB8F55F1A5BC929D219AA0D76 from 95621bb4aa63e05a23899bd596a6400a9cae04e3}
2: bcResetState{{{{11 0} 0.34.14} osmosis-1 1 2112000 2C27B002FB1D58980BFBA7BA859EA9C0F65220E7A25F0BCE512910B45EB489E7:6:20EAA4C39AA7 2021-11-23 19:09:53.688890796 +0000 UTC ValidatorSet{
  Proposer: Validator{E23AFCF0035FB01ACD02FE96F680066974D7072B PubKeyEd25519{D601D0FA5338D6BCD586AC6FC0AFE096D20C748880D8ACEB2AEED126B639AFB4} VP:73372 A:-29973792}
`

**Comment by faddat** [comment]
@dualsystems I think it's a question of ConsensusVersion somewhere in the app and I'm not real sure that it is possible/good/okay to simply change it in the code you're using to state sync from.  Love where your mind is at, though.  

Statesync is really the way.

I now do relaying from a state synced Gaia.

**Comment by faddat** [comment]
#642

**Comment by dualsystems** [comment]
@faddat  I can upload small snapshots from https://bootstrap.dual.systems/ to ipfs. But for download and deploy 1Gb snapshot more simply via http imho.

**Comment by faddat** [comment]
Actually on Osmo right now, it isn't possible to state sync. 

Best option is looking like #647 which is lookin 🔥

**Comment by dualsystems** [comment]
SDK is fixed: https://github.com/tendermint/tendermint/pull/7463
