### ISSUE TITLE
Allow proposals with different voting period lengths

### ISSUE THREAD

**Issue by sunnya97** [osmosis-labs/osmosis#567]
3 days is too short for most votes.  Should allow proposals with a couple options for voting period length, and charge a higher deposit for shorter voting period lengths.

**Comment by ValarDragon** [comment]
Fully agreed. Can you write up a more thorough design and put it on the SDK?

**Comment by ValarDragon** [comment]
I think theres a fair amount of edge cases here to consider. E.g. its odd if for one type of proposal the community expects a 7 day voting period, but then one week someone puts a 3 day voting period. Should everyone vote no? How do you ensure this becomes glaringly evident in all platforms, etc.

Would be preferrable if you have categories that form over time that mandate certain min durations, that are each distinct.

**Comment by faddat** [comment]
I think 3 days is fine for most votes, AND I think this is a super-useful feature.

**Comment by mconcat** [comment]
We still need a single proposal queue that is sorted by the end time, and don't need to have queue per voting time? Seems like the problem is more on how to allocate each proposal type to the voting times. Should we have another voting type that indicates that the proposal is invalid(as they should have been proposed in a different form), instead of voting simple nay?

**Comment by ValarDragon** [comment]
Done by @alexanderbez !
