### ISSUE TITLE
Speedup CI

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#575]
Wanted to open this issue for brainstorming on strategies for speeding up CI. Waiting on CI can easily break flow, and is a very unproductive usage of time. Some ideas:

* Split up testing into more independent tests
* Investigate strategies for parallelism in tests
* Make an automerge tag/system, that merges automatically once tests pass
* Investigate getting dependencies cached for go tests

**Comment by daniel-farina** [comment]
@ValarDragon 

I would like to start by making a list of all current Github Actions. We will eventually document each of them, give them proper names, etc. 

-  Compile Osmosis
-  Fmt
-  Lint
-  Release
-  State Sync
-  Sync test
-  Tests / Code Coverage
-  blocks per second
-  docker


Another list for additional CI pipelines we would like to have: 

- Documentation build & deploy CI (Currently in the works)
- Automated Regression Testing (Automated visual testing to make sure the UI is not broken in different browsers)

Cheers

**Comment by ValarDragon** [comment]
Great idea re listing all actions / high level deciding which ones we should add!

Sync test means fast sync right?

For blocks per second, should we be thinking of that in terms of the simulator, or mainnet? (E.g. non-blocking test, that runs the simulator for N minutes, and expects some certain minimum blocks per second time?)

Is there anything to test with docker, if statesync is listed separately?

> I noticed you tagged circleCI. Do you have in mind moving the build and release pipelines to CircleCI?

Uhh good question. Not really sure why when I made the label, I called it CircleCI. Should probably be renamed to Github Actions, AFAIU circle CI won't speedup anything.

**Comment by faddat** [comment]
@daniel-farina 

This is a good start.   

Another solution is a build server, but there are tradeoffs.

**Build Server**

Plus: We can use it with github actions
Minus: We lose forkability because other people do not have our build server.  We end up with additional dependencies (one on a machine)

**Actions**

Plus: Forkable and github default
Minus:  There really are many things you can't do easily in github actions, for example, automated testnets with real state.  The state is just too large and the thing explodes some.
