### ISSUE TITLE
dev-UX: Automatically close stale issues created by `Check Broken Links` action 

### ISSUE THREAD

**Issue by pysel** [osmosis-labs/osmosis#5806]
## Background

We have a [github workflow](https://github.com/osmosis-labs/osmosis/blob/main/.github/workflows/check-broken-links.yml) that searches for broken links in the repository and creates an issue that lists all broken links found. It runs approximately every 2 weeks. 

This results that every 2 weeks an updated issue gets created, however, the old ones still sit in Issues list. 

## Suggested Design

I think it would be nice to automatically close them after an updated report is submitted, or after some time since the creation of this issue has elapses (15 days, for example). Not sure about the best way to go with here.

## Acceptance Criteria

`Broken Links Detected` issues do not get piled up.

**Comment by inFocus7** [comment]
Hmm, i think it's reasonable to close the issues every 15 days / every day we generate a new broken link issue.

Not sure if using the [stale](https://github.com/marketplace/actions/close-stale-issues#only-labels) action is overkill (since I'm not sure how much processing and build minutes it'll cost), or if we'd just want to run a small `sh`.

But going the stale action route, we could probably add an extra step in the existing broken link workflow to go like:
1. Close any stale `issues` with the `broken link bot` label (or just any unique label for them) and write message that if broken links exist there's a new issue for it. [any-of-labels check](https://github.com/marketplace/actions/close-stale-issues#only-labels), [stale bot message field](https://github.com/marketplace/actions/close-stale-issues#only-labels)
2. Create a new issue, if any, with the above unique label

**Comment by inFocus7** [comment]
I created a PR for this, but its untested and would likely need to run the workflow/action to make sure it works as expected. It should _theoretically_ work, but I couldn't find examples in the `stale` action documentation to automatically close issues...
