### ISSUE TITLE
CW Pools: Majority of store model methods not implemented

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#6316]
## Background

See https://github.com/osmosis-labs/osmosis/blob/ef1a8ba9a7d277447924511b4b670c882d0bfc27/x/cosmwasmpool/model/store_model.go#L33-L85

## Suggested Design

Implement these methods just like the other store models

## Acceptance Criteria

All methods return the expected values

**Comment by p0mvn** [comment]
This is intended as `CosmWasmPool` is a store model for serialization only.

There is a `Pool` model that encapsulates this and the `WasmKeeper`:
https://github.com/osmosis-labs/osmosis/blob/ef1a8ba9a7d277447924511b4b670c882d0bfc27/x/cosmwasmpool/model/pool.go#L16-L19

`Pool` implements all the relevant methods.

This is because we cannot serialize `Pool` when it has `WasmKeeper` as a field.

Let's change this issue to instead focus on improving documentation around this.
