### ISSUE TITLE
Osmosis Bash Installer

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/osmosis#647]
Bash Installer to setup an Osmosis full node and test node eventually. 

- [ ] Add the following options
  - [ ]  Mainnet/Testnest
  - [ ] Sync methods
    - [x] Snapshot
      - [x] Select QuickSync network: default. pruned, archive
      - [x] Select region
    - [ ] State Sync
    - [ ] Replay from Genesis (not at all needed for a v1, but more as a long term thing to be able to configure as well).
  - [ ]  Select version
  - [x]  Update golang version (if applicable)
  - [x]  Update ~/.profile variables
- [x] Create a sample installer
- [x] Create an url to easily execute via curl and a  custom domain ex: setup.osmosis.zone
  - [x]  Create service to serve script
  - [x]  Create dns entry
  - [x]  Document this and make an open source repo for it

Current prototype: 
[https://github.com/osmosis-labs/awesome/tree/main/tools/bash_installer](https://github.com/osmosis-labs/awesome/tree/main/tools/bash_installer)

![image](https://user-images.githubusercontent.com/13665117/145520786-78411086-2795-4872-aa03-4def71887eca.png)

**Comment by ValarDragon** [comment]
Amazing, I'm so excited about this landing! (Also love the block font vibe 😎 )

I'd suggest altering it slightly to have the "installation configuration" system, rust-like (including screenshot)
and maybe the configuration 'axis' are:

* Mainnet/Testnet
* Sync method (state sync, snapshot, replay from genesis)
* History pruning method (aggressive pruning, default, archive)
* (If snapshot sync): mirror to use

(Replay from genesis not at all needed for a v1, but more as a long term thing to be able to configure as well)

**Comment by faddat** [comment]
![image](https://user-images.githubusercontent.com/7142025/145584731-e917040f-7bbe-49db-ab87-97d656ad1b5d.png)

**Comment by daniel-farina** [comment]
Thank you for the detailed feedback. I updated the task list with your improvements.  

**Question:** 
> * (If snapshot sync): mirror to use

What would be a good example of mirrors to use for snapshot?

**Comment by ValarDragon** [comment]
oh I meant what you were saying for DNS. The things supported by chainlayer, Singapore, SanFrancisco, Netherlands

**Comment by czarcas7ic** [comment]
V2 must include (for a release in the next couple of days)
- [ ] OS Specific commands (mainly concerned about Mac)
- [ ] Swap file automation

V3 must include (for a release in the next couple of weeks)
- [ ] State Sync (I'm trying to hold out for the fix to be more permanent, but I can include the temp fix for now)
- [ ] Pruning methods (aggressive pruning, default, archive)
- [ ] Replay from genesis (this wont be fun to test or automate. Will have to find a way to capture the chain halting due to version mismatch, update version, then restart)

The only current "issue" I have with the installer is it slightly relies on a "magic number" (it does an init override to create a default config.toml for the testnet. This config file includes the two mainnet seeds. It then does a find and replace for the seeds line with those two seeds and then replaces with the testnet seed. If the default mainnet seeds change, this find and replace no longer works. As I'm typing this, the best solution would probably be to just change it in osmosisd so if someone specifies chain id for testnet when doing an init, the seeds line will instead include the testnet seeds so the find and replace is no longer needed. Will talk with @ValarDragon on how to accomplish this. I know there is a find and replace for a partial match, however for some reason in python subprocess this command gets botched. Unsure why.)

The replay will also be interesting to figure out, but I don't think it will be impossible. It may get pushed to a V3 though. Please lmk if you have any other suggestions @daniel-farina

**Comment by daniel-farina** [comment]
Work for this will continue on #745  & #746
