### ISSUE TITLE
[VS Incentives]: Consider abstracting gauge logic into a general interface for extensibility

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#6499]
## Background

Carried over from [this discussion](https://github.com/osmosis-labs/osmosis/pull/6366#discussion_r1325683894) started by @p0mvn.

"I think one of the struggles with regular gauges is extending them with the new functionality. Since those were implemented as a concrete struct, we had to extend them by creating new fields resulting in a bloated abstraction.

To prevent that happening with GroupGauge in the future, do you think it makes sense to implement it as an interface (proto Any) and separate each implementation based on splitting policy.

This would make it easier to extend in the future if needed. It will also avoid having the code smell of deciding the execution flow based on splitting policy via if/else. Instead, we could implement a method on the group gauge. The concrete implementation would be chosen dynamically based on type."

## Suggested Design

For example, this
``` go
func (k Keeper) syncGroupGaugeWeights(ctx sdk.Context, groupGauge types.GroupGauge) error {
	if groupGauge.SplittingPolicy == types.Volume {
		err := k.syncVolumeSplitGauge(ctx, groupGauge)
		if err != nil {
			return err
		}
	} else {
		return types.UnsupportedSplittingPolicyError{GroupGaugeId: groupGauge.GroupGaugeId, SplittingPolicy: groupGauge.SplittingPolicy}
	}

	return nil
}
```

would become this:

``` go
volumeSplittingGauge := ...
volumeSplittingGauge.syncWeights(ctx)

evenSplittingGauge := ...
evenSplittingGauge.syncWeights(ctx)
```

## Acceptance Criteria

Issue is discussed and converged on. If we decide to implement, then interface is implemented and well tested.

**Comment by p0mvn** [comment]
Thanks for tracking this @AlpinYukseloglu 

On more thinking, while I think that this is a clean pattern overall, there are certain issues present that make it less preferred here.

For example, since `syncWeights` accesses store, it will also have to take in a keeper as parameter in addition to context.

Like this:
```go
volumeSplittingGroup.syncWeights(ctx, k) // k is incentives keeper
```

Since `Group` is defined in `types`, any internal unexported method defined on the incentives keeper would be inaccessible and have to be exported.

As a result, I think we should be good to close this. Please let me know if disagreement
