### ISSUE TITLE
[VS Incentives]: remove gauge creation logic from `CreateGroup`, call `CreateGauge` instead

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#6513]
**Context**
Logic in `CreateGroup` essentially duplicaed gauge creation.

We should instead encapsulated any gauge creation inside `CreateGauge` and call that from `CreateGroup`

**A/C**
- Create group gauge in `CreateGauge` & update tests
- Call `CreateGauge` from `CreateGroup`
- Minimize code duplication

**Comment by AlpinYukseloglu** [comment]
I agree with avoiding duplicate code, but we should be careful about storing group gauges in state alongside regular gauges since we fetch all active gauges from state for distribution using a prefix iterator:
https://github.com/osmosis-labs/osmosis/blob/9691451190364d3afb482c7e2431e9872343f400/x/incentives/keeper/hooks.go#L51

This means if we use `CreateGauge` for group gauges and by extension share keys/prefixes between group gauges and regular gauges, we should be careful to either skip group gauges during this distribution logic or in some other way exclude them from the regular gauge iterator

**Comment by p0mvn** [comment]
This is a valid concern. However, a workaround was fond and tracked:
- In `CreateGauge`, if the gauge being created is a `ByGroup` gauge, do NO create upcoming/active/finished ref keys. Only write it to a regular gauge index.
- This will allow `ByGroup` bypassing being retrieved from state via `GetActiveGauges` because it reads from a store index that `ByGroup` was written to: https://github.com/osmosis-labs/osmosis/blob/1e83ec9e392b7b8d5ca79db378ad2abe745c2762/x/incentives/keeper/gauge.go#L317


Additionally, we must write the `ByGroup` gauge intro a regular gauge index. Otherwise, we would not be able to retrieve it in a general way from pool incentive hooks when distributing from the `DisrRecord`s :https://github.com/osmosis-labs/osmosis/blob/58e1d3e98584db7dbd9e423fe93443582e8b3aef/x/incentives/keeper/gauge.go#L424

Lmk if this doesn't address your concern

**Comment by AlpinYukseloglu** [comment]
It does, great!
