### ISSUE TITLE
Fix package in `proto/osmosis/gamm`

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#761]
Currently the gamm module proto package has room for the two following fixes before we get it into a new release. 
1. fix package for genesis proto to osmosis.gamm.v1beta1 
 https://github.com/osmosis-labs/osmosis/blob/main/proto/osmosis/gamm/v1beta1/genesis.proto#L2 

2. change package structure so that pool-models goes under gamm/v1beta1.

Both changes would be state-breaking.

**Comment by ValarDragon** [comment]
I'm actually not sure that the genesis.proto one is state or genesis breaking. It is breaking the genesis proto struct, however we use genesis json's which atm don't contain the type fields. 

The package structure for pool-params is def state breaking, but since the pool models isn't on mainnet, no need for migration.
