### ISSUE TITLE
[Bug]: archive node /cosmos/staking/v1beta1/pool fails on old blocks

### ISSUE THREAD

**Issue by gilxgil** [osmosis-labs/osmosis#7675]
### What happened?

We are querying an archive node at block 12m: `/cosmos/staking/v1beta1/pool` and it returns:
```
{"code":13,"message":"invalid denom: ","details":[]}
```

Newer blocks work as expected (13m for example):
```
{"pool":{"not_bonded_tokens":"14127857404284","bonded_tokens":"335061758936683"}}
```

### Osmosis Version

latest

### How to reproduce?

Query the node at 12m block height, example:
```
curl -X GET -H "Content-Type: application/json" -H "x-cosmos-block-height: 12000000" https://archive-node/cosmos/staking/v1beta1/pool
```

**Comment by mattverse** [comment]
hey @gilxgil, does the same error occur in any of the blocks prior to block height 12m?

**Comment by gilxgil** [comment]
Yes, same results all the way to genesis.
I did a binary search and this is where the problem starts (maybe it coincides with an upgrade). 

Working block 12834100:
```
{"pool":{"not_bonded_tokens":"13862733148321","bonded_tokens":"335222421855613"}}
```

Not working block and lower 12834099:
```
{"code":13,"message":"invalid denom: ","details":[]}
```

**Comment by czarcas7ic** [comment]
It does coincide with the v21 upgrade, which is the upgrade that we unforked the sdk

**Comment by czarcas7ic** [comment]
I looked into this, its because the query calls GetParams, which prior to v21 was store in the legacyparams store, but now we store and retrieve from the individual ParamsKey of the specific module.

We could probably add a logic gate that pulls from legacyparams IFF the response is nil/zero

**Comment by czarcas7ic** [comment]
This issue exists for every query that revolves around the legacy param store

**Comment by czarcas7ic** [comment]
For anyone planning to work on it:

We call BondDenom here https://github.com/osmosis-labs/cosmos-sdk/blob/734f99fba785cc04bfd369baf6123a5a6e182b9a/x/staking/keeper/grpc_query.go#L453

Which pulls from the module params here https://github.com/osmosis-labs/cosmos-sdk/blob/9345069d96188b8e38e8e21a8296546662b70909/x/staking/keeper/params.go#L34C1-L37C2

Prior to v21, we would pull from paramstore https://github.com/osmosis-labs/cosmos-sdk/blob/734f99fba785cc04bfd369baf6123a5a6e182b9a/x/staking/keeper/params.go#L36C1-L40C2

So because the per module param store didn't exist prior to v21, it returns blank for the denom. A solution could be in the querier, if the params returns is blank, we fall back to pulling params from the legacyparamstore

**Comment by ValarDragon** [comment]
This isn't forked code correct? If so, imo we should put it in the SDK? (Any change we make here, I'd also want to get into the SDK)

The real solution for this is to have queries like this to an archive node get sent to different binaries based on block hegiht requested, rather than a single archive for all versions

**Comment by ValarDragon** [comment]
Going to close, with the solution needed is that we need tooling to make an archive node / architecture that makes a separate DB per app version. I am told Cosmosia has tooling for this. https://github.com/cosmos/cosmos-sdk/issues/12686

**Comment by PaddyMc** [comment]
Closing as this was reopened by mistake
