### ISSUE TITLE
Pardon, could you please tell me when will I get my refund back?

### ISSUE THREAD

**Issue by tangyuan2323** [osmosis-labs/osmosis#7945]
## Issue
I withdraw my BLD token from Osmo to Agoric, but it failed, I want wo know when will I get my fund back. You may refer to the img as below:

![image](https://github.com/osmosis-labs/osmosis/assets/70282618/1ecee2f7-bb7d-49bc-b4fa-de99ded80b3d)
The Tx harsh :  5CE3D2EFE20DF6247038F81ADDCDC2DD1445082BFEB60F5D071C40CC94211260

**Comment by ValarDragon** [comment]
Closing this github issue since this isn't the right spot for this, the Telegram or Discord is the place. 

On quick skim of Mintscan, it looks like this should have gotten to Agoric though, perhaps check your wallet? https://www.mintscan.io/osmosis/tx/5CE3D2EFE20DF6247038F81ADDCDC2DD1445082BFEB60F5D071C40CC94211260?height=14667281
