### ISSUE TITLE
Upgrade handlers for v7

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#802]
Hi, I might be wrong here, but seems that the sdk team may have a recommended format for these:

https://github.com/cosmos/cosmos-sdk/commit/222fd6cd358b05af8ba08deb64f7ee311c91755f

**Comment by ValarDragon** [comment]
Thanks for catching this!

Basically what they're doing is saying "make your FromVM the new SDK v0.45.x consensus versions", instead of taking fromVM as an argument which should be correctly set if your prior version was on SDK v0.44.x

It _should_ be perfectly fine to take fromVM from the argument (and much safer), and the only reason you were ever supposed to do this was SDK 42 -> 44 or greater.

We should double check, but my understanding of the upgrade code is that you shouldn't do this if your chain is already on SDK 44
