### ISSUE TITLE
Relaying Documentation

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#876]
at https://github.com/notional-labs/notional we've got a good deal of osmosis-centric relaying documentation including ready to go hermes configs.

@daniel-farina would you like this in docs/relaying?

I'd need to clean it up somewhat but I reckon that might be useful.

Also, I'm ready to fully document rocksdb usage-- where in the docs folder do you figure that should land?

**Comment by daniel-farina** [comment]
@faddat 
That would be great. I'm thinking long term we might add an IBC section and then move the relayer docs inside of it. 

For now it could go here:
https://docs.osmosis.zone/developing/

For rocksdb we have the following docs:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/13665117/154234074-c264ece9-d709-4516-b497-3017c386f443.png">

Ha! so I think adding it under [developing](https://docs.osmosis.zone/developing/) makes sense as well for now. This will be very useful as well!

Let me know if you have any questions while adding it. Here is a recent PR that shows what takes place in order to create a new section. 

Thank you!

**Comment by ValarDragon** [comment]
I believe adam added some relaying docs since this issue was made! https://docs.osmosis.zone/developing/relaying/relay.html#cosmos-hub-daemon-settings
