### ISSUE TITLE
Investigate and fix panics on fast iavl branch

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#892]
**Background**

Validators are experiencing issues on the new fast node branch with panics such as:
![image](https://user-images.githubusercontent.com/34196718/154586262-2a0d56e3-ad2d-43a5-aa7a-dd21f864c199.png)

This is an issue to investigate and fix the problems reported.

**Acceptance Criteria**
- [x] gather all information from the #validators channel on Discord and document here
- [x] investigate and document the steps taken here
- [x] if applicable, create a PR with the fix and update 6.x branch

**Comment by UnityChaos** [comment]
Replicated some of this by using a misalignment between pruning and snapshot settings, so that node would crash when attempting to prune an old height. On restart the node would rerun the previous block, but get a different result in the `distribution.keeper.allocation.AllocateTokens` function.

First run on `v6.3.0` (crashes because of trying to delete block being held for snapshot)
![1-6 3 0-start-block-90](https://user-images.githubusercontent.com/86889904/154587909-19d7f2f1-5dba-4b29-a727-90735a796fef.png)

![2-6 3 0-end-block-90-crash](https://user-images.githubusercontent.com/86889904/154587926-68ae63a1-4126-4821-92d8-70fdb09c7314.png)

Restart after disabling snapshot. Note the different `feesCollected` amounts. This seems to be connected to the `insufficient funds` error when the new value is higher than the old value, and the `already saved to different hash` error if the result is lower than the original.

![3-6 3 0-restart-block-90](https://user-images.githubusercontent.com/86889904/154587933-787a217e-02fa-4981-af65-ab9eb7a48844.png)
![4-6 3 0-finish-90-crash](https://user-images.githubusercontent.com/86889904/154588203-0b5f81d4-4848-4ca6-b197-07e8fb94f2f5.png)


---

Then reran this process on v6.2.0, and things ran as expected.

First run through, crashing because of trying to delete snapshot:

![5-6 2 0-start-block-40](https://user-images.githubusercontent.com/86889904/154588392-867c0a7d-3135-434c-b389-cfbfd982aeeb.png)
![6-6 2 0-mid-block-40](https://user-images.githubusercontent.com/86889904/154588396-afea95bd-a776-4945-923b-df1e1b0dcbe2.png)
![7-6 2 0-end-block-40](https://user-images.githubusercontent.com/86889904/154588398-ba9d1899-b80e-46f3-9acc-0c3aa432bb47.png)

Restart (after disabling snapshots) and makes it through:
![8-6 2 0-restart-block-40](https://user-images.githubusercontent.com/86889904/154588491-3ed817cb-bfc8-4929-976a-56edc6b0aecf.png)

![9-6 2 0-finish-block-40](https://user-images.githubusercontent.com/86889904/154588497-45cbf4eb-a3dc-41a1-b36d-550a5a75a747.png)

----

Not clear to me what the cause is yet, but I would imagine it's some sort of incomplete state write which is not properly reverted during the crash, is still around when the node attempts to rerun the block, leading to different results.

Also worth noting that the above situation was constructed to replicate this error, but my understanding is that node operators are hitting these errors during regular operation, not immediately after recovering from a crash as I am here.

**Comment by p0mvn** [comment]
A suggestion on how to track inconsistencies across stores:
![image](https://user-images.githubusercontent.com/34196718/154741809-30af5095-bb22-4deb-8402-105073522703.png)

**Comment by ValarDragon** [comment]
Can we detect whether were replaying a block vs executing a new block? If we're replaying a block then don't enable fast cache?

**Comment by p0mvn** [comment]
I'm trying to see why replaying a block is breaking things. The fast nodes should still stay consistent with the actual nodes even if we are replaying

**Comment by p0mvn** [comment]
PR with the fix: https://github.com/osmosis-labs/cosmos-sdk/pull/115

**Comment by p0mvn** [comment]
Still need to address the "active reader" issue related to misconfig between pruning and snapshot

**Comment by p0mvn** [comment]
[This PR](https://github.com/osmosis-labs/cosmos-sdk/pull/114) currently contains the latest changes related to this issue.

**Comment by p0mvn** [comment]
This issue seems to be resolved, closing
