### ISSUE TITLE
x/lockup: Move messageServer logic for LockTokens into keeper method

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#944]
Most of the logic for the lockup module's validations is in the message server, not the keeper.

However the keeper methods are where it should be, as its API safety that should be guaranteed for everything using the lockup module.

**Comment by voluntatis-summ** [comment]
were you thinking of moving it to the x/lockup/keeper.go file?

**Comment by stackman27** [comment]
Hi @ValarDragon, just making sure, the goal of this issue is to move [this](https://github.com/osmosis-labs/osmosis/blob/20cfa05c105c0fabef1150ce3d0687bbebb99d32/x/lockup/keeper/msg_server.go#L26-L53) logic to [this](https://github.com/osmosis-labs/osmosis/blob/20cfa05c105c0fabef1150ce3d0687bbebb99d32/x/lockup/keeper/lock.go#L118) function right?  What other validation checks are there?
